export interface CostBreakdown {
  accommodation: number;
  food: number;
  transport: number;
  activities: number;
  total: number;
}

export interface City {
  id: string;
  name: string;
  state: string;
  description: string;
  bestTime: string;
  attractions: string[];
  food: string[];
  experiences: string[];
  hotels: string[];
  resorts: string[];
  lounges: string[];
  restaurants: string[];
  costPerDay: {
    budget: CostBreakdown;
    mid: CostBreakdown;
    luxury: CostBreakdown;
  };
  rating: number;
  reviews: number;
  image: string;
  latitude: number;
  longitude: number;
}

const createCostBreakdown = (
  acc: number,
  food: number,
  trans: number,
  act: number
): CostBreakdown => ({
  accommodation: acc,
  food,
  transport: trans,
  activities: act,
  total: acc + food + trans + act,
});

export const INDIA_DESTINATIONS: City[] = [
  // Andhra Pradesh
  {
    id: "hyderabad",
    name: "Hyderabad",
    state: "Andhra Pradesh",
    description: "City of pearls with stunning architecture and IT hub",
    bestTime: "October to February",
    attractions: [
      "Charminar",
      "Mecca Masjid",
      "Golconda Fort",
      "Hussain Sagar Lake",
    ],
    food: [
      "Hyderabadi Biryani",
      "Haleem",
      "Nihari",
      "Mirchi ka Salan",
    ],
    experiences: [
      "Old City exploration",
      "Tech park tours",
      "Lake cruises",
      "Shopping at Laad Bazaar",
    ],
    hotels: [
      "Taj Falaknuma Palace",
      "The Oberoi Hotel",
      "ITC Kohenur",
      "Novotel Hyderabad",
      "Hotel Deccan Charters",
    ],
    resorts: [
      "Hyderabad Airport Hotel & Resort",
      "Oasis Retreat Resort",
      "Gateway Resort Hyderabad",
      "Kingdom of Dreams Resort",
    ],
    lounges: [
      "Vapour Lounge & Bar",
      "Galito's Smokehouse",
      "Prohibition 0.20",
      "Café Noor",
      "Mood Coffee Lounge",
    ],
    restaurants: [
      "Biryani by Rajadhani",
      "Chutneys Hyderabadi Cuisine",
      "Kamat Hotel",
      "Cream Stone",
      "The Deccan Delicacies",
      "Shah Ghouse Biryani Restaurant",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 600, 250, 400),
      luxury: createCostBreakdown(1500, 1200, 500, 800),
    },
    rating: 4.4,
    reviews: 2843,
    image: "/images/states/andhra-pradesh/hyderabad.jpg",
    latitude: 17.3850,
    longitude: 78.4867,
  },
  {
    id: "tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    description: "Sacred pilgrimage destination with spiritual significance",
    bestTime: "September to March",
    attractions: [
      "Tirupati Balaji Temple",
      "Chandragiri Fort",
      "Sri Ranganathaswamy Temple",
      "Kalyana Mandapam",
    ],
    food: [
      "Prasadam",
      "Andhra curries",
      "Puri",
      "Rice preparations",
    ],
    experiences: ["Temple visits", "Fort exploration", "Spiritual rituals", "Local markets"],
    hotels: [
      "Fortune Hotels Tirupati",
      "Hotel Bliss",
      "Ramada by Wyndham",
      "Park Regis Tirupati",
    ],
    resorts: [
      "The Maple Hill Resort",
      "Tirupati Hill Resort",
      "Aravind Resort",
    ],
    lounges: [
      "Café Tirupati",
      "Sacred Lounge",
      "Devotion Coffee Café",
    ],
    restaurants: [
      "Tirupati Tempura",
      "Ananya Restaurant",
      "Pure Vegetarian Restaurant",
      "Navratna Multi Cuisine",
    ],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 150),
      mid: createCostBreakdown(600, 400, 200, 300),
      luxury: createCostBreakdown(1200, 800, 400, 600),
    },
    rating: 4.6,
    reviews: 3421,
    image: "/images/states/andhra-pradesh/tirupati.jpg",
    latitude: 13.1886,
    longitude: 79.1295,
  },
  {
    id: "vizag",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    description: "Coastal city with beaches, hills and industrial charm",
    bestTime: "October to March",
    attractions: [
      "Beaches",
      "Araku Valley",
      "Borra Caves",
      "Kailasagiri",
    ],
    food: [
      "Fish curries",
      "Gongura pickle",
      "Prawn preparations",
      "Coastal specialties",
    ],
    experiences: ["Beach relaxation", "Hill station visits", "Cave exploration", "Sunset views"],
    hotels: [
      "Taj Gateway Hotel Vizag",
      "Novotel Visakhapatnam Varun Beach",
      "The Park Hotel",
      "Meghamalai Resort Hotel",
    ],
    resorts: [
      "Devi Resort",
      "Vizag Beach Resort",
      "Dolphin's Nose Resort",
      "Araku Valley Resort",
    ],
    lounges: [
      "Blue Horizon Lounge",
      "Coastal Café",
      "Gateway Lounge",
      "Beach House Bar",
    ],
    restaurants: [
      "Thalassa",
      "The Eatery",
      "Kamat Restaurants",
      "Seafood Harbour",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 500, 220, 350),
      luxury: createCostBreakdown(1300, 900, 420, 700),
    },
    rating: 4.3,
    reviews: 2156,
    image: "/images/states/andhra-pradesh/vizag.jpg",
    latitude: 17.6869,
    longitude: 83.2185,
  },
  {
    id: "warangal",
    name: "Warangal",
    state: "Andhra Pradesh",
    description: "Historic city with ancient temples and fort ruins",
    bestTime: "October to February",
    attractions: [
      "Warangal Fort",
      "Thousand Pillar Temple",
      "Ramappa Temple",
      "Eturnagaram Wildlife Sanctuary",
    ],
    food: [
      "Goat biryani",
      "Puran poli",
      "Local curries",
      "Rice dishes",
    ],
    experiences: ["Temple tours", "Fort exploration", "Wildlife viewing", "Heritage walks"],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 140),
      mid: createCostBreakdown(550, 400, 180, 280),
      luxury: createCostBreakdown(1000, 700, 350, 550),
    },
    rating: 4.2,
    reviews: 1245,
    image: "/images/states/andhra-pradesh/warangal.jpg",
    latitude: 17.9689,
    longitude: 78.6294,
  },

  // Arunachal Pradesh
  {
    id: "itanagar",
    name: "Itanagar",
    state: "Arunachal Pradesh",
    description: "Capital with Buddhist monasteries and hill station views",
    bestTime: "October to April",
    attractions: [
      "Itanagar Citadel",
      "Ganga Lake",
      "Craft Centre",
      "Jawaharlal Nehru Museum",
    ],
    food: [
      "Momos",
      "Thukpa",
      "Bamboo shoots",
      "Local fish curry",
    ],
    experiences: [
      "Monastery visits",
      "Lake trekking",
      "Craft shopping",
      "Cultural immersion",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 200, 250),
      mid: createCostBreakdown(1000, 600, 350, 500),
      luxury: createCostBreakdown(1800, 1100, 600, 900),
    },
    rating: 4.1,
    reviews: 856,
    image: "/images/states/arunachal-pradesh/itanagar.jpg",
    latitude: 28.2204,
    longitude: 93.6164,
  },
  {
    id: "tawang",
    name: "Tawang",
    state: "Arunachal Pradesh",
    description: "Serene hill station with Buddhist heritage and monasteries",
    bestTime: "April to October",
    attractions: [
      "Tawang Monastery",
      "Nuranang Falls",
      "Sela Pass",
      "Tawang Lake",
    ],
    food: [
      "Momos",
      "Thukpa",
      "Pork preparations",
      "Local vegetables",
    ],
    experiences: [
      "Monastery trekking",
      "Waterfall visits",
      "Mountain views",
      "Buddhist culture",
    ],
    costPerDay: {
      budget: createCostBreakdown(600, 400, 250, 300),
      mid: createCostBreakdown(1200, 700, 400, 600),
      luxury: createCostBreakdown(2000, 1200, 700, 1100),
    },
    rating: 4.7,
    reviews: 1523,
    image: "/images/states/arunachal-pradesh/tawang.jpg",
    latitude: 27.5844,
    longitude: 91.5755,
  },
  {
    id: "dibrugarh",
    name: "Dibrugarh",
    state: "Arunachal Pradesh",
    description: "Gateway to Arunachal with tea gardens and river views",
    bestTime: "November to March",
    attractions: [
      "Brahmaputra River",
      "Namphake Scenic Park",
      "Kharsang Hill",
      "Dibru-Saikhowa National Park",
    ],
    food: [
      "Hilsa fish",
      "Local curries",
      "Rice preparations",
      "Tea culture",
    ],
    experiences: [
      "River cruises",
      "Park exploration",
      "Tea estate tours",
      "Bird watching",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.0,
    reviews: 645,
    image: "/images/states/arunachal-pradesh/dibrugarh.jpg",
    latitude: 27.4728,
    longitude: 94.9142,
  },

  // Assam
  {
    id: "guwahati",
    name: "Guwahati",
    state: "Assam",
    description: "Gateway to Northeast India with Brahmaputra River charm",
    bestTime: "October to April",
    attractions: [
      "Kamakhya Temple",
      "Assam State Museum",
      "Brahmaputra River",
      "Umananda Island",
    ],
    food: [
      "Assamese fish curry",
      "Pitha",
      "Doi",
      "Bamboo shoot preparations",
    ],
    experiences: [
      "Temple visits",
      "River cruises",
      "Museum tours",
      "Local food",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.2,
    reviews: 1876,
    image: "/images/states/assam/guwahati.jpg",
    latitude: 26.1445,
    longitude: 91.7362,
  },
  {
    id: "kaziranga",
    name: "Kaziranga",
    state: "Assam",
    description: "Wildlife sanctuary famous for one-horned rhinos",
    bestTime: "November to April",
    attractions: [
      "Kaziranga National Park",
      "One-horned Rhino",
      "Elephant Safari",
      "Tiger spotting",
    ],
    food: [
      "Fish curry",
      "Rice preparations",
      "Local meat dishes",
      "Tea",
    ],
    experiences: [
      "Safari tours",
      "Wildlife photography",
      "Elephant rides",
      "Bird watching",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 200, 300),
      mid: createCostBreakdown(1000, 650, 350, 600),
      luxury: createCostBreakdown(1800, 1100, 600, 1000),
    },
    rating: 4.6,
    reviews: 2143,
    image: "/images/states/assam/kaziranga.jpg",
    latitude: 26.6122,
    longitude: 93.1544,
  },
  {
    id: "shillong",
    name: "Shillong",
    state: "Meghalaya",
    description: "Abode of clouds with waterfalls and cool climate",
    bestTime: "April to October",
    attractions: [
      "Cherrapunji",
      "Khasi Hills",
      "Living Root Bridges",
      "Elephant Falls",
    ],
    food: [
      "Jadoh",
      "Doh khlai",
      "Bamboo shoot curry",
      "Local pork",
    ],
    experiences: [
      "Waterfall trekking",
      "Living bridge walks",
      "Cloud forest exploration",
      "Local markets",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 350, 150, 220),
      mid: createCostBreakdown(850, 600, 250, 450),
      luxury: createCostBreakdown(1600, 1100, 500, 900),
    },
    rating: 4.5,
    reviews: 2567,
    image: "/images/states/meghalaya/shillong.jpg",
    latitude: 25.5788,
    longitude: 91.8933,
  },

  // Bihar
  {
    id: "patna",
    name: "Patna",
    state: "Bihar",
    description: "Historic city on Ganges with Buddhist pilgrimage sites",
    bestTime: "October to March",
    attractions: [
      "Mahabodhi Temple",
      "Bodh Gaya",
      "Nalanda Ruins",
      "Patna Museum",
    ],
    food: [
      "Sattu",
      "Litti Chokha",
      "Fish curry",
      "Kheer",
    ],
    experiences: [
      "Temple visits",
      "Archaeological exploration",
      "Ghat walks",
      "Cultural heritage tours",
    ],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 150),
      mid: createCostBreakdown(600, 450, 200, 300),
      luxury: createCostBreakdown(1200, 850, 400, 600),
    },
    rating: 4.3,
    reviews: 1654,
    image: "/images/states/bihar/patna.jpg",
    latitude: 25.5941,
    longitude: 85.1376,
  },
  {
    id: "bodh-gaya",
    name: "Bodh Gaya",
    state: "Bihar",
    description: "Most sacred Buddhist pilgrimage site in India",
    bestTime: "October to March",
    attractions: [
      "Mahabodhi Temple",
      "Bodhi Tree",
      "Temple Museum",
      "Meditation centers",
    ],
    food: [
      "Simple vegetarian meals",
      "Tea",
      "Local sweets",
      "Rice preparations",
    ],
    experiences: [
      "Meditation",
      "Temple rituals",
      "Spiritual retreats",
      "Peaceful walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(250, 200, 80, 120),
      mid: createCostBreakdown(500, 350, 150, 250),
      luxury: createCostBreakdown(1000, 700, 300, 500),
    },
    rating: 4.7,
    reviews: 3245,
    image: "/images/states/bihar/bodh-gaya.jpg",
    latitude: 24.6953,
    longitude: 84.9883,
  },
  {
    id: "rajgir",
    name: "Rajgir",
    state: "Bihar",
    description: "Historic hill station with ancient ruins and Buddhist sites",
    bestTime: "September to March",
    attractions: [
      "Nalanda University",
      "Gridhakuta Peak",
      "Hot Springs",
      "Ancient monasteries",
    ],
    food: [
      "Local curries",
      "Rice dishes",
      "Vegetarian meals",
      "Sweets",
    ],
    experiences: [
      "Peak trekking",
      "Hot spring baths",
      "Monastery visits",
      "Historical tours",
    ],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 140),
      mid: createCostBreakdown(600, 400, 180, 280),
      luxury: createCostBreakdown(1100, 750, 350, 550),
    },
    rating: 4.4,
    reviews: 1123,
    image: "/images/states/bihar/rajgir.jpg",
    latitude: 25.3508,
    longitude: 85.4331,
  },

  // Chhattisgarh
  {
    id: "raipur",
    name: "Raipur",
    state: "Chhattisgarh",
    description: "Capital city with rich tribal culture and temples",
    bestTime: "October to March",
    attractions: [
      "Laxmanpur Temple",
      "Naya Raipur",
      "Mahant Ghasidas Museum",
      "Swami Vivekananda Sarovar",
    ],
    food: [
      "Chikhalwali",
      "Fafda jalebi",
      "Local curries",
      "Rice-based dishes",
    ],
    experiences: [
      "Temple visits",
      "Museum exploration",
      "Tribal culture",
      "City tours",
    ],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 140),
      mid: createCostBreakdown(600, 400, 180, 280),
      luxury: createCostBreakdown(1100, 750, 350, 550),
    },
    rating: 4.0,
    reviews: 987,
    image: "/images/states/chhattisgarh/raipur.jpg",
    latitude: 21.2514,
    longitude: 81.6296,
  },
  {
    id: "jagdalpur",
    name: "Jagdalpur",
    state: "Chhattisgarh",
    description: "Gateway to Bastar with waterfalls and tribal villages",
    bestTime: "October to March",
    attractions: [
      "Chitrakoot Falls",
      "Tiratgarh Falls",
      "Kanger Ghati National Park",
      "Tribal markets",
    ],
    food: [
      "Bamboo shoots",
      "Local meat curry",
      "Rice dishes",
      "Tribal specialties",
    ],
    experiences: [
      "Waterfall trekking",
      "Tribal village visits",
      "Market exploration",
      "Wildlife viewing",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 160),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.3,
    reviews: 1456,
    image: "/images/states/chhattisgarh/jagdalpur.jpg",
    latitude: 19.0708,
    longitude: 81.7894,
  },
  {
    id: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    description: "Cleanest city in India with culture and commerce",
    bestTime: "October to March",
    attractions: [
      "Rajwada Palace",
      "Lal Baag Palace",
      "Holkar Museum",
      "Khandan Prayag Ghat",
    ],
    food: [
      "Poha",
      "Samosa",
      "Khichdi",
      "Jalebi",
    ],
    experiences: [
      "Palace tours",
      "Museum visits",
      "Food exploration",
      "Shopping",
    ],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 140),
      mid: createCostBreakdown(600, 400, 180, 280),
      luxury: createCostBreakdown(1100, 750, 350, 550),
    },
    rating: 4.2,
    reviews: 1823,
    image: "/images/states/madhya-pradesh/indore.jpg",
    latitude: 22.7196,
    longitude: 75.8577,
  },

  // Goa
  {
    id: "panaji",
    name: "Panaji",
    state: "Goa",
    description: "Charming capital with Portuguese architecture and beaches",
    bestTime: "November to March",
    attractions: [
      "Church of Our Lady of Immaculate Conception",
      "Miramar Beach",
      "Fort Aguada",
      "Spice plantations",
    ],
    food: [
      "Fish curry rice",
      "Prawn balchao",
      "Sorpotel",
      "Bebinca",
    ],
    experiences: [
      "Beach relaxation",
      "Church exploration",
      "Spice plantation tours",
      "Water sports",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 400, 200, 300),
      mid: createCostBreakdown(1000, 700, 300, 500),
      luxury: createCostBreakdown(2000, 1300, 600, 1000),
    },
    rating: 4.5,
    reviews: 3456,
    image: "/images/states/goa/panaji.jpg",
    latitude: 15.4909,
    longitude: 73.8278,
  },
  {
    id: "north-goa",
    name: "North Goa",
    state: "Goa",
    description: "Beach paradise with nightlife and water activities",
    bestTime: "November to March",
    attractions: [
      "Baga Beach",
      "Anjuna Beach",
      "Fort Aguada",
      "Calangute Beach",
    ],
    food: [
      "Seafood specialties",
      "Goan curry",
      "Feni drinks",
      "Local fish",
    ],
    experiences: [
      "Beach parties",
      "Water sports",
      "Flea markets",
      "Club hopping",
    ],
    costPerDay: {
      budget: createCostBreakdown(600, 500, 250, 400),
      mid: createCostBreakdown(1200, 800, 350, 600),
      luxury: createCostBreakdown(2500, 1500, 700, 1200),
    },
    rating: 4.6,
    reviews: 4123,
    image: "/images/states/goa/north-goa.jpg",
    latitude: 15.5633,
    longitude: 73.8050,
  },
  {
    id: "south-goa",
    name: "South Goa",
    state: "Goa",
    description: "Peaceful beaches with backwater beauty",
    bestTime: "November to March",
    attractions: [
      "Colva Beach",
      "Palolem Beach",
      "Cabo de Rama Fort",
      "Backwaters",
    ],
    food: [
      "Seafood curry",
      "Rice preparations",
      "Local fish",
      "Coconut specialties",
    ],
    experiences: [
      "Beach relaxation",
      "Backwater tours",
      "Dolphin spotting",
      "Fort exploration",
    ],
    costPerDay: {
      budget: createCostBreakdown(450, 350, 180, 250),
      mid: createCostBreakdown(900, 600, 280, 450),
      luxury: createCostBreakdown(1800, 1200, 550, 900),
    },
    rating: 4.4,
    reviews: 2876,
    image: "/images/states/goa/south-goa.jpg",
    latitude: 15.3302,
    longitude: 73.9339,
  },

  // Gujarat
  {
    id: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    description: "City of crafts and kites with rich heritage",
    bestTime: "October to February",
    attractions: [
      "Sabarmati Ashram",
      "Bada Bazaar",
      "Calico Museum",
      "Jama Masjid",
    ],
    food: [
      "Dhokla",
      "Fafda jalebi",
      "Khichdi",
      "Undhiyu",
    ],
    experiences: [
      "Heritage walks",
      "Kite festival",
      "Museum tours",
      "Shopping",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 500, 220, 350),
      luxury: createCostBreakdown(1300, 900, 420, 700),
    },
    rating: 4.3,
    reviews: 2145,
    image: "/images/states/gujarat/ahmedabad.jpg",
    latitude: 23.0225,
    longitude: 72.5714,
  },
  {
    id: "girnar",
    name: "Girnar",
    state: "Gujarat",
    description: "Sacred mountain with pilgrimage trails and temples",
    bestTime: "October to March",
    attractions: [
      "Girnar Mountain",
      "Neminath Temple",
      "Adinath Temple",
      "Sacred caves",
    ],
    food: [
      "Simple vegetarian meals",
      "Local breads",
      "Rice dishes",
      "Beverages",
    ],
    experiences: [
      "Mountain trekking",
      "Temple visits",
      "Spiritual retreats",
      "Dawn hikes",
    ],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 130),
      mid: createCostBreakdown(550, 400, 180, 260),
      luxury: createCostBreakdown(1000, 700, 350, 500),
    },
    rating: 4.4,
    reviews: 1234,
    image: "/images/states/gujarat/girnar.jpg",
    latitude: 21.5245,
    longitude: 71.6383,
  },
  {
    id: "rann-of-kutch",
    name: "Rann of Kutch",
    state: "Gujarat",
    description: "White desert landscape and tribal culture",
    bestTime: "November to February",
    attractions: [
      "White Salt Desert",
      "Tribal camps",
      "Crafts villages",
      "Mirror salt formations",
    ],
    food: [
      "Bajra roti",
      "Local meat curry",
      "Milk products",
      "Traditional sweets",
    ],
    experiences: [
      "Desert trekking",
      "Craft shopping",
      "Tribal interactions",
      "Sunset viewing",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.5,
    reviews: 1876,
    image: "/images/states/gujarat/rann-of-kutch.jpg",
    latitude: 23.7339,
    longitude: 71.2872,
  },

  // Haryana
  {
    id: "chandigarh",
    name: "Chandigarh",
    state: "Haryana",
    description: "Planned city with parks and modern amenities",
    bestTime: "October to March",
    attractions: [
      "Rock Garden",
      "Sukhna Lake",
      "Capitol Complex",
      "Sector 17",
    ],
    food: [
      "Chole bhature",
      "Momos",
      "Tandoori chicken",
      "Lassi",
    ],
    experiences: [
      "Garden tours",
      "Lake walks",
      "Shopping",
      "Museum visits",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.3,
    reviews: 2341,
    image: "/images/states/haryana/chandigarh.jpg",
    latitude: 30.7333,
    longitude: 76.7794,
  },
  {
    id: "morni-hills",
    name: "Morni Hills",
    state: "Haryana",
    description: "Hill station with lakes and adventure activities",
    bestTime: "September to March",
    attractions: [
      "Tilyar Lake",
      "Morni Fort",
      "Adventure sports",
      "Paragliding spots",
    ],
    food: [
      "Local curries",
      "Parathas",
      "Tandoori items",
      "Dairy products",
    ],
    experiences: [
      "Trekking",
      "Paragliding",
      "Lake fishing",
      "Adventure sports",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 220),
      mid: createCostBreakdown(800, 500, 250, 400),
      luxury: createCostBreakdown(1500, 900, 500, 800),
    },
    rating: 4.4,
    reviews: 1245,
    image: "/images/states/haryana/morni-hills.jpg",
    latitude: 30.6333,
    longitude: 77.1833,
  },

  // Himachal Pradesh
  {
    id: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    description: "Queen of the hills with colonial charm",
    bestTime: "March to June, September to October",
    attractions: [
      "Ridge",
      "Christ Church",
      "Kali Bari Temple",
      "Jakhu Temple",
    ],
    food: [
      "Parathas",
      "Madra",
      "Chikhalwali",
      "Apple preparations",
    ],
    experiences: [
      "Mall walk",
      "Temple visits",
      "Cable car rides",
      "Mountain trekking",
    ],
    costPerDay: {
      budget: createCostBreakdown(600, 400, 200, 300),
      mid: createCostBreakdown(1100, 700, 300, 500),
      luxury: createCostBreakdown(2000, 1200, 600, 1000),
    },
    rating: 4.6,
    reviews: 4567,
    image: "/images/states/himachal-pradesh/shimla.jpg",
    latitude: 31.7744,
    longitude: 77.1891,
  },
  {
    id: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    description: "Adventure hub with mountains, rivers and culture",
    bestTime: "March to June, September to October",
    attractions: [
      "Rohtang Pass",
      "Hadimba Temple",
      "Mall Road",
      "Solang Valley",
    ],
    food: [
      "Parathas",
      "Trout curry",
      "Local meat dishes",
      "Chikhalwali",
    ],
    experiences: [
      "Paragliding",
      "River rafting",
      "Mountain trekking",
      "Mountain biking",
    ],
    costPerDay: {
      budget: createCostBreakdown(600, 400, 200, 300),
      mid: createCostBreakdown(1100, 700, 300, 500),
      luxury: createCostBreakdown(2000, 1200, 600, 1000),
    },
    rating: 4.7,
    reviews: 5234,
    image: "/images/states/himachal-pradesh/manali.jpg",
    latitude: 32.2396,
    longitude: 77.1887,
  },
  {
    id: "dharamshala",
    name: "Dharamshala",
    state: "Himachal Pradesh",
    description: "Home of Dalai Lama with spiritual significance",
    bestTime: "March to June, September to October",
    attractions: [
      "Tsuglagkhang Complex",
      "Namgyal Monastery",
      "Triund Trek",
      "Bhagsu Nag Temple",
    ],
    food: [
      "Tibetan momos",
      "Thukpa",
      "Local curries",
      "Bread",
    ],
    experiences: [
      "Spiritual retreats",
      "Monastery visits",
      "Mountain trekking",
      "Meditation",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 150, 250),
      mid: createCostBreakdown(1000, 600, 250, 450),
      luxury: createCostBreakdown(1800, 1100, 500, 900),
    },
    rating: 4.6,
    reviews: 3421,
    image: "/images/states/himachal-pradesh/dharamshala.jpg",
    latitude: 32.2206,
    longitude: 76.3263,
  },
  {
    id: "kullu",
    name: "Kullu",
    state: "Himachal Pradesh",
    description: "Valley of gods with fruit orchards and adventure",
    bestTime: "March to June, September to October",
    attractions: [
      "Dhalpur Maidan",
      "Bijli Mahadev Temple",
      "Raghunath Temple",
      "Himalayan Craft",
    ],
    food: [
      "Parathas",
      "Local meat curry",
      "Fruit products",
      "Chikhalwali",
    ],
    experiences: [
      "Valley trekking",
      "Paragliding",
      "Dussehra festival",
      "Shopping",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 150, 250),
      mid: createCostBreakdown(950, 600, 250, 450),
      luxury: createCostBreakdown(1700, 1000, 500, 850),
    },
    rating: 4.5,
    reviews: 2876,
    image: "/images/states/himachal-pradesh/kullu.jpg",
    latitude: 32.2206,
    longitude: 77.1122,
  },

  // Jharkhand
  {
    id: "ranchi",
    name: "Ranchi",
    state: "Jharkhand",
    description: "Waterfall city with lush landscapes",
    bestTime: "September to March",
    attractions: [
      "Jamshedpur Waterfalls",
      "Jonha Falls",
      "Dassam Falls",
      "Patratu Dam",
    ],
    food: [
      "Litti chokha",
      "Dhuska",
      "Local curries",
      "Rice dishes",
    ],
    experiences: [
      "Waterfall trekking",
      "Dam exploration",
      "Nature walks",
      "Photography",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.2,
    reviews: 1345,
    image: "/images/states/jharkhand/ranchi.jpg",
    latitude: 23.3645,
    longitude: 85.3096,
  },
  {
    id: "jamshedpur",
    name: "Jamshedpur",
    state: "Jharkhand",
    description: "Steel city with industrial heritage and museums",
    bestTime: "October to March",
    attractions: [
      "Dimna Lake",
      "Jubilee Park",
      "Tata Steel Museum",
      "Jamshedpur Zoos",
    ],
    food: [
      "Local meat curry",
      "Rice preparations",
      "Fish curry",
      "Traditional sweets",
    ],
    experiences: [
      "Museum tours",
      "Park visits",
      "Lake boating",
      "Zoo exploration",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.1,
    reviews: 1123,
    image: "/images/states/jharkhand/jamshedpur.jpg",
    latitude: 22.8046,
    longitude: 86.1815,
  },

  // Karnataka
  {
    id: "bangalore",
    name: "Bangalore",
    state: "Karnataka",
    description: "Silicon Valley of India with gardens and culture",
    bestTime: "October to March",
    attractions: [
      "Vidhana Soudha",
      "Bannerghatta National Park",
      "Lumbini Garden",
      "Ulsoor Lake",
    ],
    food: [
      "Dosa",
      "Idli",
      "Sambar",
      "Bisi bele bath",
    ],
    experiences: [
      "Park exploration",
      "Garden walks",
      "Museum tours",
      "Nightlife",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 400, 200, 300),
      mid: createCostBreakdown(1000, 700, 300, 500),
      luxury: createCostBreakdown(2000, 1300, 600, 1000),
    },
    rating: 4.4,
    reviews: 3876,
    image: "/images/states/karnataka/bangalore.jpg",
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    id: "mysore",
    name: "Mysore",
    state: "Karnataka",
    description: "City of palaces with royal heritage",
    bestTime: "October to March",
    attractions: [
      "Mysore Palace",
      "Chamundi Hills",
      "Sri Ranganathaswamy Temple",
      "Brindavan Gardens",
    ],
    food: [
      "Mysore Pak",
      "Dosa",
      "Rasam",
      "Curries",
    ],
    experiences: [
      "Palace tours",
      "Hill trekking",
      "Garden walks",
      "Temple visits",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.6,
    reviews: 3234,
    image: "/images/states/karnataka/mysore.jpg",
    latitude: 12.2958,
    longitude: 76.6394,
  },
  {
    id: "coorg",
    name: "Coorg",
    state: "Karnataka",
    description: "Coffee country with misty hills and waterfalls",
    bestTime: "July to September, December to February",
    attractions: [
      "Coffee plantations",
      "Abbey Falls",
      "Namdroling Monastery",
      "Irpu Falls",
    ],
    food: [
      "Kodava meat curry",
      "Rice preparations",
      "Local coffee",
      "Spiced dishes",
    ],
    experiences: [
      "Plantation tours",
      "Waterfall trekking",
      "Monastery visits",
      "Forest walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 150, 250),
      mid: createCostBreakdown(1000, 600, 250, 450),
      luxury: createCostBreakdown(1800, 1100, 500, 900),
    },
    rating: 4.7,
    reviews: 2876,
    image: "/images/states/karnataka/coorg.jpg",
    latitude: 12.3381,
    longitude: 75.5585,
  },

  // Kerala
  {
    id: "kochi",
    name: "Kochi",
    state: "Kerala",
    description: "Queen of the Arabian Sea with backwaters",
    bestTime: "September to March",
    attractions: [
      "Chinese Fishing Nets",
      "Fort Kochi",
      "Backwaters",
      "Jewish Synagogue",
    ],
    food: [
      "Fish curry",
      "Appam",
      "Puttu",
      "Seafood specialties",
    ],
    experiences: [
      "Backwater cruises",
      "Houseboat stays",
      "Heritage walks",
      "Water sports",
    ],
    costPerDay: {
      budget: createCostBreakdown(600, 450, 200, 300),
      mid: createCostBreakdown(1100, 750, 300, 500),
      luxury: createCostBreakdown(2100, 1300, 600, 1000),
    },
    rating: 4.7,
    reviews: 4567,
    image: "/images/states/kerala/kochi.jpg",
    latitude: 9.9312,
    longitude: 76.2673,
  },
  {
    id: "allepey",
    name: "Alleppey",
    state: "Kerala",
    description: "Venice of the East with backwater houseboat tours",
    bestTime: "November to February",
    attractions: [
      "Backwaters",
      "Houseboats",
      "Beaches",
      "Lighthouse",
    ],
    food: [
      "Prawn curry",
      "Fish stew",
      "Puttu",
      "Appam",
    ],
    experiences: [
      "Houseboat stays",
      "Backwater cruises",
      "Beach relaxation",
      "Sunset viewing",
    ],
    costPerDay: {
      budget: createCostBreakdown(700, 500, 200, 300),
      mid: createCostBreakdown(1200, 800, 300, 500),
      luxury: createCostBreakdown(2200, 1400, 600, 1100),
    },
    rating: 4.8,
    reviews: 5123,
    image: "/images/states/kerala/allepey.jpg",
    latitude: 9.4981,
    longitude: 76.3388,
  },
  {
    id: "munnar",
    name: "Munnar",
    state: "Kerala",
    description: "Tea country in the hills with cool climate",
    bestTime: "September to March",
    attractions: [
      "Tea plantations",
      "Anamudi Peak",
      "Mattupetty Dam",
      "Echo Point",
    ],
    food: [
      "Local curries",
      "Rice dishes",
      "Tea culture",
      "Fresh vegetables",
    ],
    experiences: [
      "Plantation tours",
      "Mountain trekking",
      "Dam exploration",
      "Nature walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 150, 250),
      mid: createCostBreakdown(1000, 600, 250, 450),
      luxury: createCostBreakdown(1800, 1100, 500, 900),
    },
    rating: 4.7,
    reviews: 3456,
    image: "/images/states/kerala/munnar.jpg",
    latitude: 10.5869,
    longitude: 76.7854,
  },

  // Madhya Pradesh
  {
    id: "khajuraho",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    description: "UNESCO heritage site with ornate temples",
    bestTime: "October to March",
    attractions: [
      "Khajuraho Temples",
      "Laxman Temple",
      "Kandariya Temple",
      "Western Group",
    ],
    food: [
      "Poha",
      "Local curries",
      "Bread preparations",
      "Sweets",
    ],
    experiences: [
      "Temple tours",
      "Architecture study",
      "Sunset viewing",
      "Spiritual walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.5,
    reviews: 2345,
    image: "/images/states/madhya-pradesh/khajuraho.jpg",
    latitude: 24.8504,
    longitude: 79.9193,
  },
  {
    id: "gwalior",
    name: "Gwalior",
    state: "Madhya Pradesh",
    description: "City with magnificent fort and musical heritage",
    bestTime: "October to March",
    attractions: [
      "Gwalior Fort",
      "Jai Vilas Palace",
      "Tomar Tank",
      "Saswad Temple",
    ],
    food: [
      "Poha",
      "Samosa",
      "Local curries",
      "Sweets",
    ],
    experiences: [
      "Fort exploration",
      "Palace tours",
      "Musical performances",
      "Heritage walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.3,
    reviews: 1876,
    image: "/images/states/madhya-pradesh/gwalior.jpg",
    latitude: 26.2389,
    longitude: 78.1723,
  },

  // Maharashtra
  {
    id: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    description: "Bollywood city with beaches and modern culture",
    bestTime: "October to March",
    attractions: [
      "Gateway of India",
      "Marine Drive",
      "Taj Mahal Palace",
      "Haji Ali",
    ],
    food: [
      "Vada Pav",
      "Pav Bhaji",
      "Sev Tameta",
      "Street food",
    ],
    experiences: [
      "Beach walks",
      "Shopping",
      "Nightlife",
      "Island tours",
    ],
    costPerDay: {
      budget: createCostBreakdown(600, 500, 250, 400),
      mid: createCostBreakdown(1200, 800, 350, 600),
      luxury: createCostBreakdown(2500, 1500, 700, 1200),
    },
    rating: 4.5,
    reviews: 5678,
    image: "/images/states/maharashtra/mumbai.jpg",
    latitude: 19.0760,
    longitude: 72.8777,
  },
  {
    id: "pune",
    name: "Pune",
    state: "Maharashtra",
    description: "Cultural hub with temples and hill stations nearby",
    bestTime: "October to March",
    attractions: [
      "Shaniwar Wada",
      "Aga Khan Palace",
      "Osho Ashram",
      "Parvati Hill",
    ],
    food: [
      "Misal Pav",
      "Puran Poli",
      "Local curries",
      "Chikhalwali",
    ],
    experiences: [
      "Heritage tours",
      "Hill trekking",
      "Temple visits",
      "Spiritual retreats",
    ],
    costPerDay: {
      budget: createCostBreakdown(450, 350, 180, 250),
      mid: createCostBreakdown(900, 600, 280, 450),
      luxury: createCostBreakdown(1800, 1200, 550, 900),
    },
    rating: 4.4,
    reviews: 3456,
    image: "/images/states/maharashtra/pune.jpg",
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    id: "aurangabad",
    name: "Aurangabad",
    state: "Maharashtra",
    description: "Gateway to Ajanta-Ellora caves",
    bestTime: "October to March",
    attractions: [
      "Ajanta Caves",
      "Ellora Caves",
      "Daulatabad Fort",
      "Panchakki Mill",
    ],
    food: [
      "Hyderabadi cuisine",
      "Local curries",
      "Rice dishes",
      "Sweets",
    ],
    experiences: [
      "Cave exploration",
      "Fort tours",
      "Archaeological sites",
      "Heritage walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.5,
    reviews: 2143,
    image: "/images/states/maharashtra/aurangabad.jpg",
    latitude: 19.8762,
    longitude: 75.3433,
  },

  // Manipur
  {
    id: "imphal",
    name: "Imphal",
    state: "Manipur",
    description: "Jewel of India with lakes and cultural richness",
    bestTime: "October to March",
    attractions: [
      "Loktak Lake",
      "Kali Temple",
      "State Museum",
      "Floating Phumdis",
    ],
    food: [
      "Eezhu",
      "Fish preparations",
      "Rice dishes",
      "Local vegetables",
    ],
    experiences: [
      "Lake tours",
      "Cultural performances",
      "Museum visits",
      "Local markets",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.3,
    reviews: 1234,
    image: "/images/states/manipur/imphal.jpg",
    latitude: 24.7642,
    longitude: 94.9385,
  },

  // Meghalaya
  {
    id: "cherrapunji",
    name: "Cherrapunji",
    state: "Meghalaya",
    description: "One of the wettest places on Earth with waterfalls",
    bestTime: "May to September",
    attractions: [
      "Meghalaya Falls",
      "Living root bridges",
      "Rain forests",
      "Mawsmai Cave",
    ],
    food: [
      "Bamboo shoots",
      "Local fish curry",
      "Rice dishes",
      "Vegetables",
    ],
    experiences: [
      "Waterfall trekking",
      "Cave exploration",
      "Forest walks",
      "Rain viewing",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 350, 150, 220),
      mid: createCostBreakdown(800, 600, 250, 450),
      luxury: createCostBreakdown(1500, 1100, 500, 900),
    },
    rating: 4.6,
    reviews: 1876,
    image: "/images/states/meghalaya/cherrapunji.jpg",
    latitude: 25.2540,
    longitude: 91.7304,
  },

  // Mizoram
  {
    id: "aizawl",
    name: "Aizawl",
    state: "Mizoram",
    description: "Capital on hills with cultural vibrance",
    bestTime: "October to March",
    attractions: [
      "Bamboo crafts",
      "Durtlang Hills",
      "State Museum",
      "Local markets",
    ],
    food: [
      "Bamboo shoot curry",
      "Fish preparations",
      "Rice dishes",
      "Local meat",
    ],
    experiences: [
      "Hill walks",
      "Market exploration",
      "Museum visits",
      "Cultural experiences",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.2,
    reviews: 876,
    image: "/images/states/mizoram/aizawl.jpg",
    latitude: 23.1815,
    longitude: 92.7879,
  },

  // Nagaland
  {
    id: "kohima",
    name: "Kohima",
    state: "Nagaland",
    description: "Land of festivals with tribal culture",
    bestTime: "October to March",
    attractions: [
      "Hornbill Festival",
      "Naga Village",
      "Cathedral",
      "Local markets",
    ],
    food: [
      "Naga pork curry",
      "Bamboo shoot dishes",
      "Rice preparations",
      "Fish preparations",
    ],
    experiences: [
      "Festival visits",
      "Village exploration",
      "Cultural immersion",
      "Traditional performances",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.4,
    reviews: 1123,
    image: "/images/states/nagaland/kohima.jpg",
    latitude: 25.6247,
    longitude: 94.1086,
  },

  // Odisha
  {
    id: "bhubaneswar",
    name: "Bhubaneswar",
    state: "Odisha",
    description: "Temple city with beaches nearby",
    bestTime: "October to March",
    attractions: [
      "Lingaraj Temple",
      "Odisha State Museum",
      "Udayagiri and Khandagiri Caves",
      "Beaches",
    ],
    food: [
      "Odia curry",
      "Rice dishes",
      "Chikhalwali",
      "Local fish",
    ],
    experiences: [
      "Temple tours",
      "Museum visits",
      "Cave exploration",
      "Beach relaxation",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.3,
    reviews: 1876,
    image: "/images/states/odisha/bhubaneswar.jpg",
    latitude: 20.2961,
    longitude: 85.8245,
  },
  {
    id: "puri",
    name: "Puri",
    state: "Odisha",
    description: "Pilgrimage city with beaches and temples",
    bestTime: "October to March",
    attractions: [
      "Jagannath Temple",
      "Puri Beach",
      "Raghurajpur Village",
      "Chilika Lake",
    ],
    food: [
      "Chikhalwali",
      "Fish curry",
      "Prasadam",
      "Local sweets",
    ],
    experiences: [
      "Temple visits",
      "Beach relaxation",
      "Lake tours",
      "Art village exploration",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.4,
    reviews: 2143,
    image: "/images/states/odisha/puri.jpg",
    latitude: 19.8136,
    longitude: 85.8349,
  },

  // Punjab
  {
    id: "amritsar",
    name: "Amritsar",
    state: "Punjab",
    description: "City of golden temple and rich history",
    bestTime: "October to March",
    attractions: [
      "Golden Temple",
      "Jallianwala Bagh",
      "Wagah Border",
      "Partition Museum",
    ],
    food: [
      "Chole bhature",
      "Langar food",
      "Tandoori items",
      "Lassi",
    ],
    experiences: [
      "Temple visits",
      "Border ceremony",
      "Museum exploration",
      "Food tasting",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 300, 120, 170),
      mid: createCostBreakdown(700, 500, 220, 350),
      luxury: createCostBreakdown(1300, 900, 420, 700),
    },
    rating: 4.6,
    reviews: 3456,
    image: "/images/states/punjab/amritsar.jpg",
    latitude: 31.6340,
    longitude: 74.8711,
  },
  {
    id: "ludhiana",
    name: "Ludhiana",
    state: "Punjab",
    description: "Manchester of India with industrial heritage",
    bestTime: "October to March",
    attractions: [
      "Phillour Choe",
      "Lyallpur Khalsa College",
      "Gobindgarh Fort",
      "Local markets",
    ],
    food: [
      "Chole bhature",
      "Parathas",
      "Lassi",
      "Local meat curry",
    ],
    experiences: [
      "Factory tours",
      "Fort exploration",
      "Shopping",
      "Food experience",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.1,
    reviews: 1234,
    image: "/images/states/punjab/ludhiana.jpg",
    latitude: 30.9010,
    longitude: 75.8573,
  },

  // Rajasthan
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    description: "Pink city with palaces and culture",
    bestTime: "October to March",
    attractions: [
      "City Palace",
      "Jantar Mantar",
      "Hawa Mahal",
      "Albert Hall Museum",
    ],
    food: [
      "Gatte ki sabzi",
      "Dal baati churma",
      "Mirchi ka salan",
      "Sweets",
    ],
    experiences: [
      "Palace tours",
      "Market shopping",
      "Heritage walks",
      "Temple visits",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.5,
    reviews: 4567,
    image: "/images/states/rajasthan/jaipur.jpg",
    latitude: 26.9124,
    longitude: 75.7873,
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    description: "Blue city with magnificent fort",
    bestTime: "October to March",
    attractions: [
      "Mehrangarh Fort",
      "Jaswant Thada",
      "Clock Tower",
      "Umaid Bhawan Palace",
    ],
    food: [
      "Bajra roti",
      "Ker sangri",
      "Laal maas",
      "Ghee preparations",
    ],
    experiences: [
      "Fort tours",
      "Palace exploration",
      "Old city walks",
      "Sunset viewing",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.6,
    reviews: 3456,
    image: "/images/states/rajasthan/jodhpur.jpg",
    latitude: 26.2389,
    longitude: 73.0243,
  },
  {
    id: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    description: "City of lakes with romantic ambiance",
    bestTime: "October to March",
    attractions: [
      "City Palace",
      "Lake Pichola",
      "Jagdish Temple",
      "Fateh Sagar Lake",
    ],
    food: [
      "Gatte ki sabzi",
      "Dal bati",
      "Laal maas",
      "Rajasthani sweets",
    ],
    experiences: [
      "Lake cruises",
      "Palace tours",
      "Temple visits",
      "Sunset boating",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 150, 250),
      mid: createCostBreakdown(1000, 600, 250, 450),
      luxury: createCostBreakdown(1800, 1100, 500, 900),
    },
    rating: 4.7,
    reviews: 4123,
    image: "/images/states/rajasthan/udaipur.jpg",
    latitude: 24.5854,
    longitude: 73.7125,
  },
  {
    id: "pushkar",
    name: "Pushkar",
    state: "Rajasthan",
    description: "Sacred pilgrimage town with camel fair",
    bestTime: "October to November",
    attractions: [
      "Pushkar Lake",
      "Brahma Temple",
      "Camel Fair",
      "Desert camps",
    ],
    food: [
      "Vegetarian meals",
      "Local breads",
      "Rice dishes",
      "Dairy products",
    ],
    experiences: [
      "Camel safaris",
      "Temple visits",
      "Desert camping",
      "Spiritual activities",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.4,
    reviews: 2876,
    image: "/images/states/rajasthan/pushkar.jpg",
    latitude: 26.4923,
    longitude: 74.5511,
  },

  // Sikkim
  {
    id: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    description: "Hill station with monasteries and mountains",
    bestTime: "March to May, September to November",
    attractions: [
      "Rumtek Monastery",
      "Tsomgo Lake",
      "Nathula Pass",
      "Khangchendzonga",
    ],
    food: [
      "Momos",
      "Thukpa",
      "Bamboo shoots",
      "Local vegetables",
    ],
    experiences: [
      "Monastery visits",
      "Lake trekking",
      "Mountain views",
      "Spiritual activities",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 200, 250),
      mid: createCostBreakdown(1000, 600, 350, 500),
      luxury: createCostBreakdown(1800, 1100, 600, 900),
    },
    rating: 4.6,
    reviews: 2345,
    image: "/images/states/sikkim/gangtok.jpg",
    latitude: 27.5330,
    longitude: 88.6119,
  },
  {
    id: "pelling",
    name: "Pelling",
    state: "Sikkim",
    description: "Scenic hill station with monastery views",
    bestTime: "March to May, September to November",
    attractions: [
      "Pemayangtse Monastery",
      "Khangchendzonga Falls",
      "Singshore Bridge",
      "Kanchandzanga view",
    ],
    food: [
      "Local curries",
      "Rice dishes",
      "Momos",
      "Fresh vegetables",
    ],
    experiences: [
      "Monastery walks",
      "Waterfall trekking",
      "Mountain viewing",
      "Photography",
    ],
    costPerDay: {
      budget: createCostBreakdown(450, 300, 150, 220),
      mid: createCostBreakdown(900, 550, 250, 400),
      luxury: createCostBreakdown(1600, 1000, 500, 800),
    },
    rating: 4.5,
    reviews: 1654,
    image: "/images/states/sikkim/pelling.jpg",
    latitude: 27.5854,
    longitude: 88.2636,
  },

  // Tamil Nadu
  {
    id: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    description: "City of temples with beautiful beaches",
    bestTime: "October to March",
    attractions: [
      "Kapaleeshwarar Temple",
      "Marina Beach",
      "Government Museum",
      "Fort St. George",
    ],
    food: [
      "Dosa",
      "Idli",
      "Sambar",
      "Rasam",
    ],
    experiences: [
      "Beach walks",
      "Temple visits",
      "Museum tours",
      "Shopping",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.3,
    reviews: 2876,
    image: "/images/states/tamil-nadu/chennai.jpg",
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    id: "madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    description: "Ancient city with Meenakshi temple",
    bestTime: "October to March",
    attractions: [
      "Meenakshi Temple",
      "Thirumalai Nayakkar Palace",
      "Vaigai River",
      "Mariamman Teppakulam",
    ],
    food: [
      "Jigarthanda",
      "Dosa varieties",
      "Local curries",
      "Rice dishes",
    ],
    experiences: [
      "Temple tours",
      "Palace exploration",
      "River walks",
      "Local markets",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.4,
    reviews: 2143,
    image: "/images/states/tamil-nadu/madurai.jpg",
    latitude: 9.9252,
    longitude: 78.1198,
  },
  {
    id: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    description: "Queen of hill stations with gardens",
    bestTime: "April to June, September to November",
    attractions: [
      "Nilgiri Mountain Railway",
      "Botanical Gardens",
      "Doddabetta Peak",
      "Avalanche Lake",
    ],
    food: [
      "Local curries",
      "Rice dishes",
      "Fresh vegetables",
      "Fruits",
    ],
    experiences: [
      "Mountain train rides",
      "Garden walks",
      "Peak trekking",
      "Lake boating",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 150, 250),
      mid: createCostBreakdown(1000, 600, 250, 450),
      luxury: createCostBreakdown(1800, 1100, 500, 900),
    },
    rating: 4.6,
    reviews: 3234,
    image: "/images/states/tamil-nadu/ooty.jpg",
    latitude: 11.4102,
    longitude: 76.6955,
  },

  // Telangana
  {
    id: "hyderabad-tg",
    name: "Hyderabad (Telangana)",
    state: "Telangana",
    description: "Pearl city with IT parks and cuisine",
    bestTime: "October to February",
    attractions: [
      "Charminar",
      "Ramoji Film City",
      "Tank Bund",
      "Birla Mandir",
    ],
    food: [
      "Biryani",
      "Haleem",
      "Nihari",
      "Local curries",
    ],
    experiences: [
      "Film city tours",
      "Old city exploration",
      "Temple visits",
      "Food tasting",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.4,
    reviews: 2567,
    image: "/images/states/telangana/hyderabad.jpg",
    latitude: 17.3850,
    longitude: 78.4867,
  },

  // Tripura
  {
    id: "agartala",
    name: "Agartala",
    state: "Tripura",
    description: "City with palaces and cultural sites",
    bestTime: "October to March",
    attractions: [
      "Ujjayanta Palace",
      "Kali Temple",
      "Jagannath Temple",
      "Hanuman Virhat Temple",
    ],
    food: [
      "Fish curry",
      "Rice dishes",
      "Bamboo shoots",
      "Local meat",
    ],
    experiences: [
      "Palace tours",
      "Temple visits",
      "Market exploration",
      "Cultural performances",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.2,
    reviews: 1123,
    image: "/images/states/tripura/agartala.jpg",
    latitude: 23.8103,
    longitude: 91.2788,
  },

  // Uttar Pradesh
  {
    id: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    description: "City of Taj Mahal, one of world wonders",
    bestTime: "October to March",
    attractions: [
      "Taj Mahal",
      "Agra Fort",
      "Itmad-ud-Daulah",
      "Mehtab Bagh",
    ],
    food: [
      "Chole bhature",
      "Pethe ki sabzi",
      "Pethas",
      "Biryani",
    ],
    experiences: [
      "Monument tours",
      "Fort exploration",
      "Sunrise/sunset viewing",
      "Local shopping",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.7,
    reviews: 5678,
    image: "/images/states/uttar-pradesh/agra.jpg",
    latitude: 27.1767,
    longitude: 78.0081,
  },
  {
    id: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    description: "Holy city on Ganges with spiritual significance",
    bestTime: "October to March",
    attractions: [
      "Ganges Ghat",
      "Kashi Vishwanath Temple",
      "Sarnath",
      "Manikarnika Ghat",
    ],
    food: [
      "Khichdi",
      "Chole bhature",
      "Local curries",
      "Milk preparations",
    ],
    experiences: [
      "Ghat walks",
      "Boat rides",
      "Temple visits",
      "Spiritual retreats",
    ],
    costPerDay: {
      budget: createCostBreakdown(300, 250, 100, 150),
      mid: createCostBreakdown(600, 450, 200, 300),
      luxury: createCostBreakdown(1200, 850, 400, 600),
    },
    rating: 4.6,
    reviews: 4567,
    image: "/images/states/uttar-pradesh/varanasi.jpg",
    latitude: 25.3201,
    longitude: 82.9789,
  },
  {
    id: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    description: "City of Nawabs with beautiful architecture",
    bestTime: "October to March",
    attractions: [
      "Bara Imambara",
      "Rumi Darwaza",
      "Chota Imambara",
      "State Museum",
    ],
    food: [
      "Lucknowi biryani",
      "Kebabs",
      "Shami kebab",
      "Nihari",
    ],
    experiences: [
      "Monument tours",
      "Museum visits",
      "Food tasting",
      "Heritage walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.3,
    reviews: 1876,
    image: "/images/states/uttar-pradesh/lucknow.jpg",
    latitude: 26.8467,
    longitude: 80.9462,
  },

  // Uttarakhand
  {
    id: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    description: "Yoga capital with spiritual retreats",
    bestTime: "September to November, February to March",
    attractions: [
      "Yoga studios",
      "Parmarth Niketan",
      "Laxman Jhula",
      "Ram Jhula",
    ],
    food: [
      "Vegetarian meals",
      "Local breads",
      "Fresh produce",
      "Milk products",
    ],
    experiences: [
      "Yoga classes",
      "Meditation",
      "River rafting",
      "Ashram stays",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.5,
    reviews: 3456,
    image: "/images/states/uttarakhand/rishikesh.jpg",
    latitude: 30.0893,
    longitude: 78.2679,
  },
  {
    id: "haridwar",
    name: "Haridwar",
    state: "Uttarakhand",
    description: "Gateway to gods with sacred Ghat ceremonies",
    bestTime: "September to November, February to March",
    attractions: [
      "Ghat ceremonies",
      "Har-ki-Pauri",
      "Chandi Devi Temple",
      "Mansa Devi Temple",
    ],
    food: [
      "Vegetarian meals",
      "Chikhalwali",
      "Local sweets",
      "Tea",
    ],
    experiences: [
      "Ghat rituals",
      "Aarti ceremonies",
      "Temple visits",
      "Spiritual immersion",
    ],
    costPerDay: {
      budget: createCostBreakdown(350, 280, 120, 170),
      mid: createCostBreakdown(700, 450, 220, 350),
      luxury: createCostBreakdown(1300, 850, 420, 700),
    },
    rating: 4.4,
    reviews: 2876,
    image: "/images/states/uttarakhand/haridwar.jpg",
    latitude: 29.9457,
    longitude: 78.1642,
  },
  {
    id: "nainital",
    name: "Nainital",
    state: "Uttarakhand",
    description: "Lake district in the hills",
    bestTime: "March to May, September to October",
    attractions: [
      "Naini Lake",
      "Naina Peak",
      "Temple",
      "Boat rides",
    ],
    food: [
      "Local curries",
      "Rice dishes",
      "Fresh produce",
      "Dairy products",
    ],
    experiences: [
      "Lake boating",
      "Peak trekking",
      "Shopping on Mall Road",
      "Nature walks",
    ],
    costPerDay: {
      budget: createCostBreakdown(450, 300, 150, 220),
      mid: createCostBreakdown(900, 550, 250, 400),
      luxury: createCostBreakdown(1600, 1000, 500, 800),
    },
    rating: 4.5,
    reviews: 2345,
    image: "/images/states/uttarakhand/nainital.jpg",
    latitude: 29.3919,
    longitude: 79.4542,
  },

  // West Bengal
  {
    id: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    description: "City of joy with rich cultural heritage",
    bestTime: "October to March",
    attractions: [
      "Victoria Memorial",
      "Howrah Bridge",
      "Kali Temple",
      "Indian Museum",
    ],
    food: [
      "Sandesh",
      "Luchi",
      "Fish curry",
      "Rasgulla",
    ],
    experiences: [
      "Heritage walks",
      "Museum tours",
      "Temple visits",
      "River cruises",
    ],
    costPerDay: {
      budget: createCostBreakdown(400, 300, 150, 200),
      mid: createCostBreakdown(800, 550, 250, 400),
      luxury: createCostBreakdown(1500, 1000, 500, 800),
    },
    rating: 4.4,
    reviews: 3456,
    image: "/images/states/west-bengal/kolkata.jpg",
    latitude: 22.5726,
    longitude: 88.3639,
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    description: "Hill station famous for tea and Kanchenjunga views",
    bestTime: "April to June, September to October",
    attractions: [
      "Kanchenjunga Peak",
      "Toy Train",
      "Tea gardens",
      "Tiger Hill",
    ],
    food: [
      "Momos",
      "Thukpa",
      "Tea specialties",
      "Local curries",
    ],
    experiences: [
      "Toy train rides",
      "Plantation tours",
      "Peak viewing",
      "Trek adventures",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 350, 150, 250),
      mid: createCostBreakdown(1000, 600, 250, 450),
      luxury: createCostBreakdown(1800, 1100, 500, 900),
    },
    rating: 4.7,
    reviews: 3876,
    image: "/images/states/west-bengal/darjeeling.jpg",
    latitude: 27.0360,
    longitude: 88.2663,
  },

  // Union Territories
  // Delhi
  {
    id: "delhi",
    name: "New Delhi",
    state: "Delhi",
    description: "National capital with heritage and monuments",
    bestTime: "October to March",
    attractions: [
      "Red Fort",
      "India Gate",
      "Qutb Minar",
      "Jama Masjid",
    ],
    food: [
      "Chole bhature",
      "Kebabs",
      "Paratha",
      "Street food",
    ],
    experiences: [
      "Monument tours",
      "Market exploration",
      "Museum visits",
      "Shopping",
    ],
    costPerDay: {
      budget: createCostBreakdown(500, 400, 200, 300),
      mid: createCostBreakdown(1000, 700, 300, 500),
      luxury: createCostBreakdown(2000, 1300, 600, 1000),
    },
    rating: 4.4,
    reviews: 4567,
    image: "/images/states/delhi/new-delhi.jpg",
    latitude: 28.6139,
    longitude: 77.2090,
  },

  // Ladakh
  {
    id: "leh",
    name: "Leh",
    state: "Ladakh",
    description: "High altitude adventure destination with monasteries",
    bestTime: "June to September",
    attractions: [
      "Hemis Monastery",
      "Shey Palace",
      "Pangong Lake",
      "Khardung La Pass",
    ],
    food: [
      "Momos",
      "Thukpa",
      "Bread",
      "Local meat",
    ],
    experiences: [
      "Monastery trekking",
      "High altitude cycling",
      "Lake exploration",
      "Adventure sports",
    ],
    costPerDay: {
      budget: createCostBreakdown(700, 400, 300, 400),
      mid: createCostBreakdown(1300, 700, 450, 700),
      luxury: createCostBreakdown(2200, 1200, 800, 1200),
    },
    rating: 4.8,
    reviews: 3456,
    image: "/images/states/ladakh/leh.jpg",
    latitude: 34.1526,
    longitude: 77.5771,
  },

  // Puducherry
  {
    id: "pondicherry",
    name: "Puducherry",
    state: "Puducherry",
    description: "Former French colony with beaches and culture",
    bestTime: "October to March",
    attractions: [
      "Promenade Beach",
      "Aurobindo Ashram",
      "Auroville",
      "French Quarter",
    ],
    food: [
      "Fish curry",
      "Crab preparations",
      "French cuisine",
      "Local curries",
    ],
    experiences: [
      "Beach relaxation",
      "Ashram visits",
      "Spiritual retreats",
      "Local exploration",
    ],
    costPerDay: {
      budget: createCostBreakdown(450, 350, 150, 250),
      mid: createCostBreakdown(900, 600, 250, 450),
      luxury: createCostBreakdown(1700, 1100, 500, 850),
    },
    rating: 4.4,
    reviews: 2145,
    image: "/images/states/puducherry/pondicherry.jpg",
    latitude: 12.0096,
    longitude: 79.8711,
  },

  // Andaman and Nicobar Islands
  {
    id: "port-blair",
    name: "Port Blair",
    state: "Andaman & Nicobar Islands",
    description: "Island paradise with beaches and water activities",
    bestTime: "October to May",
    attractions: [
      "Cellular Jail",
      "Ross Island",
      "Corbyn's Cove Beach",
      "Havelock Island",
    ],
    food: [
      "Fresh seafood",
      "Crab preparations",
      "Fish curry",
      "Local specialties",
    ],
    experiences: [
      "Island hopping",
      "Scuba diving",
      "Beach relaxation",
      "Water sports",
    ],
    costPerDay: {
      budget: createCostBreakdown(800, 500, 250, 400),
      mid: createCostBreakdown(1400, 800, 400, 700),
      luxury: createCostBreakdown(2400, 1400, 700, 1200),
    },
    rating: 4.6,
    reviews: 2876,
    image: "/images/states/andaman-nicobar/port-blair.jpg",
    latitude: 11.7401,
    longitude: 92.7521,
  },

  // Lakshadweep
  {
    id: "kavarati",
    name: "Kavarati",
    state: "Lakshadweep",
    description: "Island getaway with coral reefs and pristine beaches",
    bestTime: "October to May",
    attractions: [
      "Coral Reef",
      "Beaches",
      "Water sports",
      "Local island exploration",
    ],
    food: [
      "Fresh seafood",
      "Coconut curries",
      "Fish preparations",
      "Local dishes",
    ],
    experiences: [
      "Snorkeling",
      "Scuba diving",
      "Beach relaxation",
      "Island tours",
    ],
    costPerDay: {
      budget: createCostBreakdown(900, 600, 300, 400),
      mid: createCostBreakdown(1500, 900, 450, 700),
      luxury: createCostBreakdown(2500, 1500, 800, 1200),
    },
    rating: 4.5,
    reviews: 1234,
    image: "/images/states/lakshadweep/kavarati.jpg",
    latitude: 10.5667,
    longitude: 72.6417,
  },

  // Daman and Diu
  {
    id: "daman",
    name: "Daman",
    state: "Daman & Diu",
    description: "Beach destination with Portuguese heritage",
    bestTime: "October to March",
    attractions: [
      "Daman Fort",
      "Devka Beach",
      "Nani Daman",
      "Moti Daman",
    ],
    food: [
      "Fish curry",
      "Seafood",
      "Crab preparations",
      "Local curries",
    ],
    experiences: [
      "Beach relaxation",
      "Fort exploration",
      "Water sports",
      "Local markets",
    ],
    costPerDay: {
      budget: createCostBreakdown(450, 350, 150, 250),
      mid: createCostBreakdown(900, 600, 250, 450),
      luxury: createCostBreakdown(1700, 1100, 500, 850),
    },
    rating: 4.2,
    reviews: 1123,
    image: "/images/states/daman-diu/daman.jpg",
    latitude: 20.7103,
    longitude: 72.8447,
  },
];
